import { useState, useEffect } from "react";
import { useNavigate, useParams } from "react-router-dom";
import api from "../api/axios";
import { useLanguage } from "../context/LanguageContext";

const ClientForm = () => {
  const { t } = useLanguage();
  const navigate = useNavigate();
  const { id } = useParams();
  const isEditMode = !!id;

  const [formData, setFormData] = useState({
    name: "",
    nif: "",
    address: "",
    postalCode: "",
    city: "",
    province: "",
    country: "",
    phone: "",
    email: "",
    paymentMethod: "Transferencia",
    paymentTerms: "1 day",
    paymentTermsManual: "",
    contactPerson: [],
  });
  const [isLoading, setIsLoading] = useState(isEditMode);
  const [error, setError] = useState(null);

  useEffect(() => {
    if (isEditMode) {
      const fetchClient = async () => {
        try {
          const response = await api.get(`/clients/${id}`);
          setFormData(response.data);
        } catch (err) {
          setError(t("error"));
          console.error(err);
        } finally {
          setIsLoading(false);
        }
      };
      fetchClient();
    } else {
      const fetchNextNumber = async () => {
        try {
          const response = await api.get("/clients/next-number");
          setFormData((prev) => ({
            ...prev,
            clientNumber: response.data.nextNumber,
          }));
        } catch (err) {
          console.error("Error fetching next client number:", err);
        }
      };
      fetchNextNumber();
    }
  }, [id, isEditMode, t]);

  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleAddContactPerson = () => {
    setFormData({
      ...formData,
      contactPerson: [
        ...formData.contactPerson,
        { name: "", lastName: "", phoneNumber: "" },
      ],
    });
  };

  const handleRemoveContactPerson = (index) => {
    const updated = formData.contactPerson.filter((_, i) => i !== index);
    setFormData({ ...formData, contactPerson: updated });
  };

  const handleContactPersonChange = (index, field, value) => {
    const updated = formData.contactPerson.map((person, i) =>
      i === index ? { ...person, [field]: value } : person
    );
    setFormData({ ...formData, contactPerson: updated });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setIsLoading(true);
    setError(null);
    try {
      if (isEditMode) {
        await api.put(`/clients/${id}`, formData);
      } else {
        await api.post("/clients", formData);
      }
      navigate("/clients");
    } catch (err) {
      setError(err.response?.data?.message || err.message || t("error"));
      setIsLoading(false);
    }
  };

  return (
    <div className="page-container">
      <div style={{ maxWidth: "600px", margin: "0 auto" }}>
        <h1
          style={{
            fontSize: "1.875rem",
            fontWeight: "bold",
            color: "var(--color-text-main)",
            marginBottom: "1.5rem",
          }}
        >
          {isEditMode ? t("editClient") : t("newClient")}
        </h1>

        <div
          style={{
            backgroundColor: "white",
            padding: "2rem",
            borderRadius: "0.5rem",
            boxShadow: "var(--shadow-sm)",
            border: "1px solid var(--color-border)",
          }}
        >
          {error && (
            <div
              style={{
                backgroundColor: "#fee2e2",
                color: "#ef4444",
                padding: "0.75rem",
                borderRadius: "0.375rem",
                marginBottom: "1rem",
              }}
            >
              {error}
            </div>
          )}

          <form
            onSubmit={handleSubmit}
            style={{ display: "grid", gap: "1rem" }}
          >
            <div>
              <label
                style={{
                  display: "block",
                  marginBottom: "0.5rem",
                  fontWeight: "500",
                  color: "var(--color-text-secondary)",
                }}
              >
                {t("clientNumber")}
              </label>
              <input
                type="text"
                value={
                  formData.clientNumber
                    ? formData.clientNumber.toString().padStart(5, "0")
                    : t("autoGenerated")
                }
                disabled
                style={{
                  width: "100%",
                  padding: "0.5rem",
                  borderRadius: "0.375rem",
                  border: "1px solid #cbd5e1",
                  backgroundColor: "#f1f5f9",
                  cursor: "not-allowed",
                }}
              />
            </div>

            <div>
              <label
                style={{
                  display: "block",
                  marginBottom: "0.5rem",
                  fontWeight: "500",
                  color: "var(--color-text-secondary)",
                }}
              >
                {t("clientName")}
              </label>
              <input
                type="text"
                name="name"
                value={formData.name}
                onChange={handleChange}
                required
                style={{
                  width: "100%",
                  padding: "0.5rem",
                  borderRadius: "0.375rem",
                  border: "1px solid #cbd5e1",
                }}
              />
            </div>

            <div>
              <label
                style={{
                  display: "block",
                  marginBottom: "0.5rem",
                  fontWeight: "500",
                  color: "var(--color-text-secondary)",
                }}
              >
                {t("clientNIF")}
              </label>
              <input
                type="text"
                name="nif"
                value={formData.nif}
                onChange={handleChange}
                required
                style={{
                  width: "100%",
                  padding: "0.5rem",
                  borderRadius: "0.375rem",
                  border: "1px solid #cbd5e1",
                }}
              />
            </div>

            <div>
              <label
                style={{
                  display: "block",
                  marginBottom: "0.5rem",
                  fontWeight: "500",
                  color: "var(--color-text-secondary)",
                }}
              >
                {t("phone")}
              </label>
              <input
                type="text"
                name="phone"
                value={formData.phone || ""}
                onChange={handleChange}
                style={{
                  width: "100%",
                  padding: "0.5rem",
                  borderRadius: "0.375rem",
                  border: "1px solid #cbd5e1",
                }}
              />
            </div>

            <div>
              <label
                style={{
                  display: "block",
                  marginBottom: "0.5rem",
                  fontWeight: "500",
                  color: "var(--color-text-secondary)",
                }}
              >
                {t("email")}
              </label>
              <input
                type="email"
                name="email"
                value={formData.email}
                onChange={handleChange}
                style={{
                  width: "100%",
                  padding: "0.5rem",
                  borderRadius: "0.375rem",
                  border: "1px solid #cbd5e1",
                }}
              />
            </div>

            <div>
              <label
                style={{
                  display: "block",
                  marginBottom: "0.5rem",
                  fontWeight: "500",
                  color: "var(--color-text-secondary)",
                }}
              >
                {t("paymentMethod") || "Método de pago"}
              </label>
              <select
                name="paymentMethod"
                value={formData.paymentMethod}
                onChange={handleChange}
                style={{
                  width: "100%",
                  padding: "0.5rem",
                  borderRadius: "0.375rem",
                  border: "1px solid #cbd5e1",
                  backgroundColor: "white",
                  marginBottom: "1rem",
                }}
              >
                <option value="Transferencia">{t("transfer")}</option>
                <option value="Efectivo">{t("cash")}</option>
                <option value="Tarjeta">{t("card")}</option>
                <option value="Domiciliación bancaria">
                  {t("directDebit")}
                </option>
              </select>
            </div>

            <div>
              <label
                style={{
                  display: "block",
                  marginBottom: "0.5rem",
                  fontWeight: "500",
                  color: "var(--color-text-secondary)",
                }}
              >
                {t("paymentTerms")}
              </label>
              <select
                name="paymentTerms"
                value={formData.paymentTerms}
                onChange={handleChange}
                style={{
                  width: "100%",
                  padding: "0.5rem",
                  borderRadius: "0.375rem",
                  border: "1px solid #cbd5e1",
                  backgroundColor: "white",
                  marginBottom: "1rem",
                }}
              >
                <option value="1 day">{t("1 day")}</option>
                <option value="7 days">{t("7 days")}</option>
                <option value="15 days">{t("15 days")}</option>
                <option value="30 days">{t("30 days")}</option>
                <option value="45 days">{t("45 days")}</option>
                <option value="60 days">{t("60 days")}</option>
                <option value="Manual">{t("Manual")}</option>
              </select>
            </div>

            {formData.paymentTerms === "Manual" && (
              <div>
                <label
                  style={{
                    display: "block",
                    marginBottom: "0.5rem",
                    fontWeight: "500",
                    color: "var(--color-text-secondary)",
                  }}
                >
                  {t("paymentTermsManualPlaceholder")}
                </label>
                <input
                  type="text"
                  name="paymentTermsManual"
                  value={formData.paymentTermsManual}
                  onChange={handleChange}
                  required
                  style={{
                    width: "100%",
                    padding: "0.5rem",
                    borderRadius: "0.375rem",
                    border: "1px solid #cbd5e1",
                    marginBottom: "1rem",
                  }}
                />
              </div>
            )}

            <div>
              <label
                style={{
                  display: "block",
                  marginBottom: "0.5rem",
                  fontWeight: "500",
                  color: "var(--color-text-secondary)",
                }}
              >
                {t("address")}
              </label>
              <textarea
                name="address"
                value={formData.address}
                onChange={handleChange}
                rows="2"
                style={{
                  width: "100%",
                  padding: "0.5rem",
                  borderRadius: "0.375rem",
                  border: "1px solid #cbd5e1",
                  fontFamily: "inherit",
                }}
              />
            </div>

            <div
              style={{
                display: "grid",
                gridTemplateColumns: "1fr 1fr 1fr",
                gap: "1rem",
              }}
            >
              <div>
                <label
                  style={{
                    display: "block",
                    marginBottom: "0.5rem",
                    fontWeight: "500",
                    color: "var(--color-text-secondary)",
                  }}
                >
                  {t("postalCode")}
                </label>
                <input
                  type="text"
                  name="postalCode"
                  value={formData.postalCode || ""}
                  onChange={handleChange}
                  style={{
                    width: "100%",
                    padding: "0.5rem",
                    borderRadius: "0.375rem",
                    border: "1px solid #cbd5e1",
                  }}
                />
              </div>
              <div>
                <label
                  style={{
                    display: "block",
                    marginBottom: "0.5rem",
                    fontWeight: "500",
                    color: "var(--color-text-secondary)",
                  }}
                >
                  {t("city")}
                </label>
                <input
                  type="text"
                  name="city"
                  value={formData.city || ""}
                  onChange={handleChange}
                  style={{
                    width: "100%",
                    padding: "0.5rem",
                    borderRadius: "0.375rem",
                    border: "1px solid #cbd5e1",
                  }}
                />
              </div>
              <div>
                <label
                  style={{
                    display: "block",
                    marginBottom: "0.5rem",
                    fontWeight: "500",
                    color: "var(--color-text-secondary)",
                  }}
                >
                  {t("province")}
                </label>
                <input
                  type="text"
                  name="province"
                  value={formData.province || ""}
                  onChange={handleChange}
                  style={{
                    width: "100%",
                    padding: "0.5rem",
                    borderRadius: "0.375rem",
                    border: "1px solid #cbd5e1",
                  }}
                />
              </div>
              <div>
                <label
                  style={{
                    display: "block",
                    marginBottom: "0.5rem",
                    fontWeight: "500",
                    color: "var(--color-text-secondary)",
                  }}
                >
                  {t("country")}
                </label>
                <input
                  type="text"
                  name="country"
                  value={formData.country || ""}
                  onChange={handleChange}
                  style={{
                    width: "100%",
                    padding: "0.5rem",
                    borderRadius: "0.375rem",
                    border: "1px solid #cbd5e1",
                  }}
                />
              </div>
            </div>

            {/* Contact Persons Section */}
            <div style={{ marginTop: "1.5rem" }}>
              <div
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "center",
                  marginBottom: "1rem",
                }}
              >
                <label
                  style={{
                    fontWeight: "500",
                    color: "var(--color-text-secondary)",
                  }}
                >
                  {t("contactPersons")}
                </label>
                <button
                  type="button"
                  onClick={handleAddContactPerson}
                  style={{
                    backgroundColor: "var(--color-primary)",
                    color: "white",
                    padding: "0.375rem 0.75rem",
                    borderRadius: "0.375rem",
                    border: "none",
                    cursor: "pointer",
                    fontSize: "0.875rem",
                    fontWeight: "500",
                  }}
                >
                  + {t("addContactPerson")}
                </button>
              </div>

              {formData.contactPerson.map((person, index) => (
                <div
                  key={index}
                  style={{
                    border: "1px solid #e2e8f0",
                    borderRadius: "0.375rem",
                    padding: "1rem",
                    marginBottom: "1rem",
                    backgroundColor: "#f8fafc",
                  }}
                >
                  <div
                    style={{
                      display: "flex",
                      justifyContent: "space-between",
                      alignItems: "center",
                      marginBottom: "0.75rem",
                    }}
                  >
                    <h4
                      style={{
                        fontSize: "0.875rem",
                        fontWeight: "600",
                        color: "var(--color-text-secondary)",
                      }}
                    >
                      {t("contactPerson")} {index + 1}
                    </h4>
                    <button
                      type="button"
                      onClick={() => handleRemoveContactPerson(index)}
                      style={{
                        backgroundColor: "#ef4444",
                        color: "white",
                        padding: "0.25rem 0.5rem",
                        borderRadius: "0.25rem",
                        border: "none",
                        cursor: "pointer",
                        fontSize: "0.75rem",
                      }}
                    >
                      {t("remove")}
                    </button>
                  </div>

                  <div style={{ display: "grid", gap: "0.75rem" }}>
                    <div>
                      <label
                        style={{
                          display: "block",
                          marginBottom: "0.25rem",
                          fontSize: "0.875rem",
                          fontWeight: "500",
                          color: "var(--color-text-secondary)",
                        }}
                      >
                        {t("contactName")}
                      </label>
                      <input
                        type="text"
                        value={person.name}
                        onChange={(e) =>
                          handleContactPersonChange(
                            index,
                            "name",
                            e.target.value
                          )
                        }
                        required
                        style={{
                          width: "100%",
                          padding: "0.5rem",
                          borderRadius: "0.375rem",
                          border: "1px solid #cbd5e1",
                          backgroundColor: "white",
                        }}
                      />
                    </div>

                    <div>
                      <label
                        style={{
                          display: "block",
                          marginBottom: "0.25rem",
                          fontSize: "0.875rem",
                          fontWeight: "500",
                          color: "var(--color-text-secondary)",
                        }}
                      >
                        {t("contactLastName")}
                      </label>
                      <input
                        type="text"
                        value={person.lastName}
                        onChange={(e) =>
                          handleContactPersonChange(
                            index,
                            "lastName",
                            e.target.value
                          )
                        }
                        required
                        style={{
                          width: "100%",
                          padding: "0.5rem",
                          borderRadius: "0.375rem",
                          border: "1px solid #cbd5e1",
                          backgroundColor: "white",
                        }}
                      />
                    </div>

                    <div>
                      <label
                        style={{
                          display: "block",
                          marginBottom: "0.25rem",
                          fontSize: "0.875rem",
                          fontWeight: "500",
                          color: "var(--color-text-secondary)",
                        }}
                      >
                        {t("contactPhone")}
                      </label>
                      <input
                        type="text"
                        value={person.phoneNumber}
                        onChange={(e) =>
                          handleContactPersonChange(
                            index,
                            "phoneNumber",
                            e.target.value
                          )
                        }
                        required
                        style={{
                          width: "100%",
                          padding: "0.5rem",
                          borderRadius: "0.375rem",
                          border: "1px solid #cbd5e1",
                          backgroundColor: "white",
                        }}
                      />
                    </div>
                  </div>
                </div>
              ))}
            </div>

            <div
              className="flex justify-between items-center"
              style={{ marginTop: "1rem" }}
            >
              <button
                type="button"
                onClick={() => navigate("/clients")}
                style={{
                  backgroundColor: "transparent",
                  color: "var(--color-text-secondary)",
                  border: "1px solid var(--color-border)",
                  padding: "0.5rem 1rem",
                  borderRadius: "0.375rem",
                  cursor: "pointer",
                  fontWeight: "500",
                }}
              >
                {t("cancel")}
              </button>
              <button
                disabled={isLoading}
                type="submit"
                className="btn btn-primary"
              >
                {isLoading ? t("saving") : t("save")}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
};

export default ClientForm;
